import json
import re

user_pasted_text = """
📄 Article: "Infant Of A Diabetic Mother" -> [Endocrinology]
   📄 Article: "Insulin Therapy In Diabetes Mellitus Management" -> [Endocrinology]
   📄 Article: "Macrovascular And Microvascular Complications Of Diabetes" -> [Endocrinology]
   📄 Article: "Multiple Endocrine Neoplasia (MEN)" -> [Endocrinology]
   📄 Article: "Noninsulin Antihyperglycemic Drugs In Type 2 Diabetes Mellitus" -> [Endocrinology]
   📄 Article: "Osteoporosis" -> [Endocrinology]
   📄 Article: "Osteoporosis Management" -> [Endocrinology]
   📄 Article: "Paget Disease Of Bone" -> [Endocrinology]
   📄 Article: "Pancreatic Neuroendocrine Tumors (PanNETs)" -> [Endocrinology]
   📄 Article: "Parathyroid Disorders: Hyperparathyroidism And Hypoparathyroidism" -> [Endocrinology]
   📄 Article: "Pituitary Tumors" -> [Endocrinology]
   📄 Article: "Polycystic Ovary Syndrome" -> [Endocrinology]
   📄 Article: "Precocious Puberty" -> [Endocrinology]
   📄 Article: "Sheehan Syndrome" -> [Endocrinology]
   📄 Article: "Short Stature" -> [Endocrinology]
   📄 Article: "Syndrome Of Inappropriate Antidiuretic Hormone (SIADH)" -> [Endocrinology]
   📄 Article: "The Menstrual Cycle" -> [Endocrinology]
   📄 Article: "Thyroid Malignancies" -> [Endocrinology]
   📄 Article: "Thyroid Nodules" -> [Endocrinology]
   📄 Article: "Thyroid Physiology And Diagnostic Testing" -> [Endocrinology]
   📄 Article: "Thyroiditis" -> [Endocrinology]
   📄 Article: "Type 1 And 2 Diabetes Mellitus In Pregnancy" -> [Endocrinology]
   📄 Article: "Type 1 Diabetes Mellitus: An Overview" -> [Endocrinology]
   📄 Article: "Type 2 Diabetes Mellitus: An Overview" -> [Endocrinology]
   📄 Article: "Vertebral Compression Fracture" -> [Endocrinology]
   📄 Article: "Vitamin D Analogues" -> [Endocrinology]
   📄 Article: "Vitamin D Deficiency Rickets" -> [Endocrinology]
 📁 Folder: "Gastroenterology"
   📄 Article: "Abdominal Compartment Syndrome" -> [Gastroenterology]
   📄 Article: "Abdominal Pain: An Overview" -> [Gastroenterology]
   📄 Article: "Achalasia" -> [Gastroenterology]
   📄 Article: "Acid Suppression Therapy" -> [Gastroenterology]
   📄 Article: "Acute Appendicitis" -> [Gastroenterology]
   📄 Article: "Acute Cholangitis" -> [Gastroenterology]
   📄 Article: "Acute Cholecystitis" -> [Gastroenterology]
   📄 Article: "Acute Liver Failure" -> [Gastroenterology]
   📄 Article: "Adhesions" -> [Gastroenterology]
   📄 Article: "Anal Cancer" -> [Gastroenterology]
   📄 Article: "Anal Fissure" -> [Gastroenterology]
   📄 Article: "Anatomy: Layers Of The Abdominal Wall" -> [Gastroenterology]
   📄 Article: "Anatomy: Pancreas" -> [Gastroenterology]
   📄 Article: "Annular Pancreas" -> [Gastroenterology]
   📄 Article: "Anorectal Abscess" -> [Gastroenterology]
   📄 Article: "Anterior Abdominal Wall Hernias" -> [Gastroenterology]
   📄 Article: "Antiemetics" -> [Gastroenterology]
   📄 Article: "Autoimmune Hepatitis" -> [Gastroenterology]
   📄 Article: "Bariatric Surgery" -> [Gastroenterology]
   📄 Article: "Barrett Esophagus" -> [Gastroenterology]
   📄 Article: "Biliary Atresia" -> [Gastroenterology]
   📄 Article: "Bilirubin Metabolism" -> [Gastroenterology]
   📄 Article: "Breast Milk Jaundice" -> [Gastroenterology]
   📄 Article: "Carcinoid Syndrome And Well-Differentiated Neuroendocrine Tumors" -> [Gastroenterology]
   📄 Article: "Celiac Disease" -> [Gastroenterology]
   📄 Article: "Cholangiocarcinoma" -> [Gastroenterology]
   📄 Article: "Cholera" -> [Gastroenterology]
   📄 Article: "Cirrhosis" -> [Gastroenterology]
   📄 Article: "Clostridioides Difficile Infection" -> [Gastroenterology]
   📄 Article: "Colorectal Cancer" -> [Gastroenterology]
   📄 Article: "Complications Of Cirrhosis" -> [Gastroenterology]
   📄 Article: "Congenital Umbilical Hernias" -> [Gastroenterology]
   📄 Article: "Constipation" -> [Gastroenterology]
   📄 Article: "Diarrhea" -> [Gastroenterology]
   📄 Article: "Diverticular Disease: Diverticulosis, Diverticulitis, And Diverticular Bleeding" -> [Gastroenterology]
   📄 Article: "Dumping Syndrome" -> [Gastroenterology]
   📄 Article: "Duodenal Atresia" -> [Gastroenterology]
   📄 Article: "Dyspepsia" -> [Gastroenterology]
   📄 Article: "Embryology Of The Gastrointestinal System" -> [Gastroenterology]
   📄 Article: "Entamoeba Histolytica Infection (Amebiasis)" -> [Gastroenterology]
   📄 Article: "Eosinophilic Esophagitis" -> [Gastroenterology]
   📄 Article: "Esophageal Atresia And Tracheoesophageal Fistula" -> [Gastroenterology]
   📄 Article: "Esophageal Cancer" -> [Gastroenterology]
   📄 Article: "Esophageal Rupture" -> [Gastroenterology]
   📄 Article: "Esophageal Stricture" -> [Gastroenterology]
   📄 Article: "Esophagitis" -> [Gastroenterology]
   📄 Article: "Evaluation Of Abnormal Liver Function Tests (LFTs)" -> [Gastroenterology]
   📄 Article: "Failure To Thrive" -> [Gastroenterology]
   📄 Article: "Fecal Incontinence" -> [Gastroenterology]
   📄 Article: "Food Protein-Induced Allergic Proctocolitis (FPIAP)" -> [Gastroenterology]
   📄 Article: "Foodborne Illness (Food Poisoning)" -> [Gastroenterology]
   📄 Article: "Foreign Body Ingestion" -> [Gastroenterology]
   📄 Article: "Galactosemia" -> [Gastroenterology]
   📄 Article: "Galactosemia And Related Conditions" -> [Gastroenterology]
   📄 Article: "Gallstone Disease: Cholelithiasis, Choledocholithiasis, Cholecystitis, Cholangitis, And Others" -> [Gastroenterology]
   📄 Article: "Gastric Cancer" -> [Gastroenterology]
   📄 Article: "Gastroesophageal Reflux Disease (GERD)" -> [Gastroenterology]
   📄 Article: "Gastrointestinal Anatomy And Histology I: Oropharynx And Esophagus" -> [Gastroenterology]
   📄 Article: "Gastrointestinal Anatomy And Histology III: Large Intestine, Rectum/Anus" -> [Gastroenterology]
   📄 Article: "Gastrointestinal Bleed" -> [Gastroenterology]
   📄 Article: "Gastroparesis" -> [Gastroenterology]
   📄 Article: "Gastroschisis" -> [Gastroenterology]
   📄 Article: "Giardiasis" -> [Gastroenterology]
   📄 Article: "Groin Hernias" -> [Gastroenterology]
   📄 Article: "Gut Ischemia: Acute/Chronic Mesenteric Ischemia And Ischemic Colitis" -> [Gastroenterology]
   📄 Article: "Hemorrhoids" -> [Gastroenterology]
   📄 Article: "Hepatitis A, D, And E Virus Infection" -> [Gastroenterology]
   📄 Article: "Hepatitis B Virus (HBV) Infection" -> [Gastroenterology]
   📄 Article: "Hepatitis C Virus (HCV) Infection" -> [Gastroenterology]
   📄 Article: "Hepatocellular Carcinoma (And Other Hepatic Masses)" -> [Gastroenterology]
   📄 Article: "Hereditary Hyperbilirubinemias" -> [Gastroenterology]
   📄 Article: "Hiatal Hernias" -> [Gastroenterology]
   📄 Article: "Hirschsprung Disease" -> [Gastroenterology]
   📄 Article: "Infantile Colic" -> [Gastroenterology]
   📄 Article: "Inflammatory Bowel Disease (IBD):  Crohn Disease And Ulcerative Colitis" -> [Gastroenterology]
   📄 Article: "Intussusception" -> [Gastroenterology]
   📄 Article: "Irritable Bowel Syndrome (IBS)" -> [Gastroenterology]
   📄 Article: "Lactose Intolerance" -> [Gastroenterology]
   📄 Article: "Major Intestinal Helminthic Infections: Hookworm, Roundworm, Tapeworm, And Whipworm" -> [Gastroenterology]
   📄 Article: "Mallory-Weiss Syndrome" -> [Gastroenterology]
   📄 Article: "Malrotation" -> [Gastroenterology]
   📄 Article: "Meckel Diverticulum" -> [Gastroenterology]
   📄 Article: "Metabolic Dysfunction-Associated Steatotic Liver Disease (MASLD) (Formerly NAFLD)" -> [Gastroenterology]
   📄 Article: "Microscopic Colitis" -> [Gastroenterology]
   📄 Article: "Nausea And Vomiting In Pregnancy" -> [Gastroenterology]
   📄 Article: "Necrotizing Enterocolitis" -> [Gastroenterology]
   📄 Article: "Neonatal Jaundice" -> [Gastroenterology]
   📄 Article: "Norovirus Infection" -> [Gastroenterology]
   📄 Article: "Omphalocele" -> [Gastroenterology]
   📄 Article: "Pancreatic Cancer" -> [Gastroenterology]
   📄 Article: "Pancreatitis" -> [Gastroenterology]
   📄 Article: "Paralytic Ileus" -> [Gastroenterology]
   📄 Article: "Pediatric Functional Constipation" -> [Gastroenterology]
   📄 Article: "Peptic Ulcer Disease" -> [Gastroenterology]
   📄 Article: "Phenylketonuria" -> [Gastroenterology]
   📄 Article: "Physiology: Normal Digestion" -> [Gastroenterology]
   📄 Article: "Pilonidal Disease" -> [Gastroenterology]
   📄 Article: "Primary Biliary Cholangitis" -> [Gastroenterology]
   📄 Article: "Primary Sclerosing Cholangitis" -> [Gastroenterology]
   📄 Article: "Protein-Energy Malnutrition: Kwashiorkor, Marasmus, And Cachexia" -> [Gastroenterology]
   📄 Article: "Pyloric Stenosis" -> [Gastroenterology]
   📄 Article: "Pyogenic Liver Abscess" -> [Gastroenterology]
   📄 Article: "Rectal Prolapse" -> [Gastroenterology]
   📄 Article: "Rectovaginal Fistula" -> [Gastroenterology]
   📄 Article: "Refeeding Syndrome" -> [Gastroenterology]
   📄 Article: "Rotavirus" -> [Gastroenterology]
   📄 Article: "Salmonella" -> [Gastroenterology]
   📄 Article: "Shigella Infection (Shigellosis)" -> [Gastroenterology]
   📄 Article: "Small Bowel Obstruction" -> [Gastroenterology]
   📄 Article: "Small Intestinal Bacterial Overgrowth (SIBO)" -> [Gastroenterology]
   📄 Article: "Suboptimal Intake (Breastfeeding Failure) Jaundice" -> [Gastroenterology]
   📄 Article: "Superior Mesenteric Artery Syndrome" -> [Gastroenterology]
   📄 Article: "Trauma: Blunt Thoracic And Abdominal Trauma" -> [Gastroenterology]
   📄 Article: "Trauma: Penetrating Abdominal Trauma" -> [Gastroenterology]
   📄 Article: "Viscus Perforation" -> [Gastroenterology]
   📄 Article: "Vitamin Deficiencies And Toxicities" -> [Gastroenterology]
   📄 Article: "Volvulus" -> [Gastroenterology]
   📄 Article: "Wilson Disease" -> [Gastroenterology]
   📄 Article: "Zenker Diverticulum" -> [Gastroenterology]
 📁 Folder: "Gynecology"
   📄 Article: "5-Alpha Reductase Deficiency" -> [Gynecology]
   📄 Article: "Acute Cervicitis" -> [Gynecology]
   📄 Article: "Adenomyosis" -> [Gynecology]
   📄 Article: "Anatomy: Retroperitoneum" -> [Gynecology]
   📄 Article: "Androgen Insensitivity Syndrome" -> [Gynecology]
   📄 Article: "Aromatase Inhibitors" -> [Gynecology]
   📄 Article: "Bacterial Vaginosis" -> [Gynecology]
   📄 Article: "Bartholin Gland Cyst And Abscess" -> [Gynecology]
   📄 Article: "Benign Breast Disease" -> [Gynecology]
   📄 Article: "BRCA1 And BRCA2 Mutations" -> [Gynecology]
   📄 Article: "Breast Anatomy And Histology" -> [Gynecology]
   📄 Article: "Breast Cancer" -> [Gynecology]
   📄 Article: "Breastfeeding" -> [Gynecology]
   📄 Article: "Cervical Dysplasia And Cancer" -> [Gynecology]
   📄 Article: "Condyloma Acuminata" -> [Gynecology]
   📄 Article: "Congenital Uterine Anomalies" -> [Gynecology]
   📄 Article: "Contraception" -> [Gynecology]
   📄 Article: "Dyspareunia" -> [Gynecology]
   📄 Article: "Emergency Contraception" -> [Gynecology]
   📄 Article: "Endometrial Cancer" -> [Gynecology]
   📄 Article: "Endometrial Polyp" -> [Gynecology]
   📄 Article: "Endometriosis" -> [Gynecology]
   📄 Article: "Epithelial Ovarian Cancer" -> [Gynecology]
   📄 Article: "Evaluation Of A Breast Mass" -> [Gynecology]
   📄 Article: "Evaluation Of Abnormal Uterine Bleeding" -> [Gynecology]
   📄 Article: "Evaluation Of An Ovarian Mass" -> [Gynecology]
   📄 Article: "Evaluation Of Breast Pain" -> [Gynecology]
   📄 Article: "Evaluation Of Nipple Discharge" -> [Gynecology]
   📄 Article: "Evaluation Of Postmenopausal Bleeding" -> [Gynecology]
   📄 Article: "Evaluation Of Primary Amenorrhea" -> [Gynecology]
   📄 Article: "Evaluation Of Secondary Amenorrhea" -> [Gynecology]
   📄 Article: "Evaluation Of Vaginal Discharge" -> [Gynecology]
   📄 Article: "Female Reproductive System Anatomy And Histology" -> [Gynecology]
   📄 Article: "Functional Ovarian Cysts" -> [Gynecology]
   📄 Article: "Genitourinary Syndrome Of Menopause" -> [Gynecology]
   📄 Article: "Gestational Trophoblastic Neoplasia" -> [Gynecology]
   📄 Article: "GnRH Agonists (Leuprolide)" -> [Gynecology]
   📄 Article: "Gynecomastia" -> [Gynecology]
   📄 Article: "Hypothalamic Amenorrhea" -> [Gynecology]
   📄 Article: "Imperforate Hymen" -> [Gynecology]
   📄 Article: "Infectious Genital Ulcers" -> [Gynecology]
   📄 Article: "Infertility" -> [Gynecology]
   📄 Article: "Inflammatory Breast Cancer" -> [Gynecology]
   📄 Article: "Interstitial Cystitis" -> [Gynecology]
   📄 Article: "Intimate Partner Violence" -> [Gynecology]
   📄 Article: "Intraductal Papilloma" -> [Gynecology]
   📄 Article: "Intrauterine Adhesions" -> [Gynecology]
   📄 Article: "Labial Adhesions" -> [Gynecology]
   📄 Article: "Mastitis And Breast Abscess" -> [Gynecology]
   📄 Article: "Maternal And Neonatal Group B Streptococcus Infection" -> [Gynecology]
   📄 Article: "Menopause" -> [Gynecology]
   📄 Article: "Müllerian Agenesis" -> [Gynecology]
   📄 Article: "Mycoplasma Genitalium Infection" -> [Gynecology]
   📄 Article: "Neisseria Gonorrhoeae (Gonococcal) Infection" -> [Gynecology]
   📄 Article: "Normal Puberty" -> [Gynecology]
   📄 Article: "Oogenesis And Spermatogenesis" -> [Gynecology]
   📄 Article: "Ovarian Hyperstimulation Syndrome" -> [Gynecology]
   📄 Article: "Ovarian Torsion" -> [Gynecology]
   📄 Article: "Paget Disease Of The Breast" -> [Gynecology]
   📄 Article: "Pelvic Inflammatory Disease" -> [Gynecology]
   📄 Article: "Pelvic Organ Prolapse" -> [Gynecology]
   📄 Article: "Premenstrual Syndrome And Premenstrual Dysphoric Disorder" -> [Gynecology]
   📄 Article: "Primary Dysmenorrhea" -> [Gynecology]
   📄 Article: "Primary Ovarian Insufficiency" -> [Gynecology]
   📄 Article: "Rare Ovarian Tumors" -> [Gynecology]
   📄 Article: "Sarcoma Botryoides" -> [Gynecology]
   📄 Article: "Selective Estrogen Receptor Modulators (SERMs)" -> [Gynecology]
   📄 Article: "Sexual Assault" -> [Gynecology]
   📄 Article: "Sexual Dysfunction" -> [Gynecology]
   📄 Article: "Turner Syndrome" -> [Gynecology]
   📄 Article: "Urethral Diverticulum" -> [Gynecology]
   📄 Article: "Urinary Incontinence" -> [Gynecology]
   📄 Article: "Uterine Fibroids" -> [Gynecology]
   📄 Article: "Uterine Sarcoma" -> [Gynecology]
   📄 Article: "Vaginal Cancer" -> [Gynecology]
   📄 Article: "Vaginal Foreign Bodies" -> [Gynecology]
   📄 Article: "Vesicovaginal Fistula" -> [Gynecology]
   📄 Article: "Vulvar Cancer" -> [Gynecology]
   📄 Article: "Vulvar Lichen Sclerosus" -> [Gynecology]
   📄 Article: "Vulvovaginal Candidiasis" -> [Gynecology]
 📁 Folder: "Hematology & Oncology"
   📄 Article: "Acute Lymphoblastic Leukemia And Lymphoblastic Lymphoma" -> [Hematology & Oncology]
   📄 Article: "Acute Myeloid Leukemia" -> [Hematology & Oncology]
   📄 Article: "Alkylating Agents" -> [Hematology & Oncology]
   📄 Article: "Alpha Thalassemia" -> [Hematology & Oncology]
   📄 Article: "Amyloidosis" -> [Hematology & Oncology]
   📄 Article: "Anemia: Anemia Of Chronic Disease/Anemia Of Inflammation" -> [Hematology & Oncology]
   📄 Article: "Anemia: Approach To Anemia" -> [Hematology & Oncology]
   📄 Article: "Anemia: Iron Deficiency Anemia" -> [Hematology & Oncology]
   📄 Article: "Anticoagulants" -> [Hematology & Oncology]
   📄 Article: "Antifibrinolytic Agents" -> [Hematology & Oncology]
   📄 Article: "Antimetabolites" -> [Hematology & Oncology]
   📄 Article: "Antiphospholipid Syndrome" -> [Hematology & Oncology]
   📄 Article: "Antitumor Antibiotics" -> [Hematology & Oncology]
   📄 Article: "Aplastic Anemia" -> [Hematology & Oncology]
   📄 Article: "Approach To Anemia" -> [Hematology & Oncology]
   📄 Article: "Autoimmune Hemolytic Anemias" -> [Hematology & Oncology]
   📄 Article: "Basic Blood Cell Types: Erythrocytes, Leukocytes, And Platelets" -> [Hematology & Oncology]
   📄 Article: "Beta Thalassemia" -> [Hematology & Oncology]
   📄 Article: "Cancer Screening" -> [Hematology & Oncology]
   📄 Article: "Chronic Lymphocytic Leukemia" -> [Hematology & Oncology]
   📄 Article: "Chronic Myeloid Leukemia" -> [Hematology & Oncology]
   📄 Article: "Coagulation Disorders: An Overview" -> [Hematology & Oncology]
   📄 Article: "Disseminated Intravascular Coagulation" -> [Hematology & Oncology]
   📄 Article: "Factor V Leiden" -> [Hematology & Oncology]
   📄 Article: "Glucose-6-Phosphate Dehydrogenase Deficiency" -> [Hematology & Oncology]
   📄 Article: "Hairy Cell Leukemia" -> [Hematology & Oncology]
   📄 Article: "Hemochromatosis" -> [Hematology & Oncology]
   📄 Article: "Hemolytic Anemia: An Overview" -> [Hematology & Oncology]
   📄 Article: "Hemophilia A And B" -> [Hematology & Oncology]
   📄 Article: "Heparin-Induced Thrombocytopenia" -> [Hematology & Oncology]
   📄 Article: "Hereditary Hemorrhagic Telangiectasia (Osler-Weber-Rendu)" -> [Hematology & Oncology]
   📄 Article: "Hereditary Spherocytosis" -> [Hematology & Oncology]
   📄 Article: "Hodgkin Lymphoma" -> [Hematology & Oncology]
   📄 Article: "Immune Thrombocytopenia (ITP)" -> [Hematology & Oncology]
   📄 Article: "Inherited Functional Platelet Disorders" -> [Hematology & Oncology]
   📄 Article: "Lung Cancer" -> [Hematology & Oncology]
   📄 Article: "Methemoglobinemia" -> [Hematology & Oncology]
   📄 Article: "Microtubule Inhibitors" -> [Hematology & Oncology]
   📄 Article: "Monoclonal Gammopathy Of Unknown Significance" -> [Hematology & Oncology]
   📄 Article: "Multiple Myeloma" -> [Hematology & Oncology]
   📄 Article: "Myelodysplastic Syndromes" -> [Hematology & Oncology]
   📄 Article: "Myelofibrosis" -> [Hematology & Oncology]
   📄 Article: "Neuroblastoma" -> [Hematology & Oncology]
   📄 Article: "Neutropenia" -> [Hematology & Oncology]
   📄 Article: "Neutropenic Fever" -> [Hematology & Oncology]
   📄 Article: "Non-Hodgkin Lymphoma" -> [Hematology & Oncology]
   📄 Article: "Osteosarcoma" -> [Hematology & Oncology]
   📄 Article: "Paroxysmal Nocturnal Hemoglobinuria" -> [Hematology & Oncology]
   📄 Article: "Parvovirus B19 Infection" -> [Hematology & Oncology]
   📄 Article: "Penile Cancer" -> [Hematology & Oncology]
   📄 Article: "Pernicious Anemia" -> [Hematology & Oncology]
   📄 Article: "Platelet Disorders" -> [Hematology & Oncology]
   📄 Article: "Polycythemia (Erythrocytosis)" -> [Hematology & Oncology]
   📄 Article: "Porphyria" -> [Hematology & Oncology]
   📄 Article: "Protooncogenes" -> [Hematology & Oncology]
   📄 Article: "Pyruvate Kinase Deficiency" -> [Hematology & Oncology]
   📄 Article: "Renal Cell Carcinoma" -> [Hematology & Oncology]
   📄 Article: "Renal Vein Thrombosis" -> [Hematology & Oncology]
   📄 Article: "Rh Alloimmunization In Pregnancy" -> [Hematology & Oncology]
   📄 Article: "Selective IgA Deficiency" -> [Hematology & Oncology]
   📄 Article: "Sickle Cell Disease" -> [Hematology & Oncology]
   📄 Article: "Sickle Cell Disease Complications" -> [Hematology & Oncology]
   📄 Article: "Sideroblastic Anemias" -> [Hematology & Oncology]
   📄 Article: "Spleen: Anatomy And Function" -> [Hematology & Oncology]
   📄 Article: "Testicular Cancer" -> [Hematology & Oncology]
   📄 Article: "Thrombocytopenia: An Overview" -> [Hematology & Oncology]
   📄 Article: "Thrombocytopenia: Heparin-Induced Thrombocytopenia" -> [Hematology & Oncology]
   📄 Article: "Thrombocytopenia: Immune Thrombocytopenia (ITP)" -> [Hematology & Oncology]
   📄 Article: "Thrombophilias: An Overview" -> [Hematology & Oncology]
   📄 Article: "Thrombotic Microangiopathies: Thrombotic Thrombocytopenic Purpura (TTP) And Hemolytic Uremic Syndrome (HUS)" -> [Hematology & Oncology]
   📄 Article: "Thrombotic Thrombocytopenic Purpura (TTP)" -> [Hematology & Oncology]
   📄 Article: "Topoisomerase Inhibitors" -> [Hematology & Oncology]
   📄 Article: "Transfusion Reactions" -> [Hematology & Oncology]
   📄 Article: "Tumor Lysis Syndrome (TLS)" -> [Hematology & Oncology]
   📄 Article: "Tumor Suppressor Genes" -> [Hematology & Oncology]
   📄 Article: "Von Hippel-Lindau" -> [Hematology & Oncology]
   📄 Article: "Von Willebrand Disease" -> [Hematology & Oncology]
   📄 Article: "Waldenström Macroglobulinemia" -> [Hematology & Oncology]
 📁 Folder: "Infectious Diseases"
   📄 Article: "Actinomyces" -> [Infectious Diseases]
   📄 Article: "Acute HIV Infection" -> [Infectious Diseases]
   📄 Article: "African Sleeping Sickness" -> [Infectious Diseases]
   📄 Article: "Anthrax" -> [Infectious Diseases]
   📄 Article: "Antimicrobials: Antibiotics" -> [Infectious Diseases]
   📄 Article: "Antimicrobials: Antifungals" -> [Infectious Diseases]
   📄 Article: "Aspergillosis" -> [Infectious Diseases]
   📄 Article: "Babesios" -> [Infectious Diseases]
   📄 Article: "Bacteremia" -> [Infectious Diseases]
   📄 Article: "Bacterial Meningitis (Age >1 Month)" -> [Infectious Diseases]
   📄 Article: "Bacterial Toxins" -> [Infectious Diseases]
   📄 Article: "Bartonella Henselae Infections" -> [Infectious Diseases]
   📄 Article: "Basic Bacteriology: Structure, Virulence Factors, And Genetics" -> [Infectious Diseases]
   📄 Article: "Basic Virology" -> [Infectious Diseases]
   📄 Article: "Blastomycosis" -> [Infectious Diseases]
   📄 Article: "Bordetella Pertussis" -> [Infectious Diseases]
   📄 Article: "Botulism" -> [Infectious Diseases]
   📄 Article: "Brain Abscess" -> [Infectious Diseases]
   📄 Article: "Brucellosis" -> [Infectious Diseases]
   📄 Article: "Campylobacter" -> [Infectious Diseases]
   📄 Article: "Candida Infections" -> [Infectious Diseases]
   📄 Article: "Chikungunya Fever" -> [Infectious Diseases]
   📄 Article: "Chlamydia Trachomatis" -> [Infectious Diseases]
   📄 Article: "Coccidioidomycosis" -> [Infectious Diseases]
   📄 Article: "Conjunctivitis" -> [Infectious Diseases]
   📄 Article: "Corynebacterium Diphtheriae Infection (Diphtheria)" -> [Infectious Diseases]
   📄 Article: "Cryptococcal Meningoencephalitis" -> [Infectious Diseases]
   📄 Article: "Cytomegalovirus (CMV)" -> [Infectious Diseases]
   📄 Article: "Dengue Virus Infection" -> [Infectious Diseases]
   📄 Article: "Ebola" -> [Infectious Diseases]
   📄 Article: "Ehrlichia And Anaplasma" -> [Infectious Diseases]
   📄 Article: "Encephalitis" -> [Infectious Diseases]
   📄 Article: "Endophthalmitis" -> [Infectious Diseases]
   📄 Article: "Escherichia Coli" -> [Infectious Diseases]
   📄 Article: "Fournier Gangrene" -> [Infectious Diseases]
   📄 Article: "Haemophilus Influenzae" -> [Infectious Diseases]
   📄 Article: "Herpes Simplex Virus (HSV)" -> [Infectious Diseases]
   📄 Article: "Herpes Zoster (Shingles)" -> [Infectious Diseases]
   📄 Article: "Histoplasmosis" -> [Infectious Diseases]
   📄 Article: "HIV Antiretroviral Therapy (ART) And The Immune Reconstitution Inflammatory Syndrome (IRIS)" -> [Infectious Diseases]
   📄 Article: "HIV In Pregnancy" -> [Infectious Diseases]
   📄 Article: "HIV Lifecycle" -> [Infectious Diseases]
   📄 Article: "HIV-Associated Neurocognitive Disorders" -> [Infectious Diseases]
   📄 Article: "Human Papillomavirus (HPV)" -> [Infectious Diseases]
   📄 Article: "Infections Of The Hand" -> [Infectious Diseases]
   📄 Article: "Infectious Mononucleosis" -> [Infectious Diseases]
   📄 Article: "Infectious Urethritis" -> [Infectious Diseases]
   📄 Article: "Isolation Precautions" -> [Infectious Diseases]
   📄 Article: "Japanese Encephalitis" -> [Infectious Diseases]
   📄 Article: "Legionella Disease" -> [Infectious Diseases]
   📄 Article: "Leishmaniasis" -> [Infectious Diseases]
   📄 Article: "Leprosy (Hansen Disease):  Mycobacterium Leprae Infection" -> [Infectious Diseases]
   📄 Article: "Leptospirosis" -> [Infectious Diseases]
   📄 Article: "Listeriosis" -> [Infectious Diseases]
   📄 Article: "Loiasis (Loa Loa Infection)" -> [Infectious Diseases]
   📄 Article: "Lyme Disease" -> [Infectious Diseases]
   📄 Article: "Lymphatic Filariasis" -> [Infectious Diseases]
   📄 Article: "Malaria" -> [Infectious Diseases]
   📄 Article: "Mediastinitis" -> [Infectious Diseases]
   📄 Article: "Melioidosis" -> [Infectious Diseases]
   📄 Article: "Mold-Related Illness" -> [Infectious Diseases]
   📄 Article: "Mpox" -> [Infectious Diseases]
   📄 Article: "Mumps" -> [Infectious Diseases]
   📄 Article: "Necrotizing Fasciitis" -> [Infectious Diseases]
   📄 Article: "Neisseria Meningitidis (Meningococcal Meningitis)" -> [Infectious Diseases]
   📄 Article: "Neonatal Sepsis" -> [Infectious Diseases]
   📄 Article: "Nocardia" -> [Infectious Diseases]
   📄 Article: "Nontuberculous Mycobacteria (NTM)" -> [Infectious Diseases]
   📄 Article: "Onchocerciasis (River Blindness)" -> [Infectious Diseases]
   📄 Article: "Osteomyelitis" -> [Infectious Diseases]
   📄 Article: "Overview Of Protozoal Infections And Antiprotozals" -> [Infectious Diseases]
   📄 Article: "Paracoccidioidomycosis" -> [Infectious Diseases]
   📄 Article: "Parapneumonic Effusion And Empyema" -> [Infectious Diseases]
   📄 Article: "Pediatric Urinary Tract Infections" -> [Infectious Diseases]
   📄 Article: "Pinworm Infection (Enterobiasis)" -> [Infectious Diseases]
   📄 Article: "Pneumocystis Jirovecii Pneumonia" -> [Infectious Diseases]
   📄 Article: "Pneumonia" -> [Infectious Diseases]
   📄 Article: "Poliomyelitis" -> [Infectious Diseases]
   📄 Article: "Postoperative Fever" -> [Infectious Diseases]
   📄 Article: "Preseptal Cellulitis" -> [Infectious Diseases]
   📄 Article: "Pseudomonas" -> [Infectious Diseases]
   📄 Article: "Q Fever (Coxiella Burnetii Infection)" -> [Infectious Diseases]
   📄 Article: "Rabies" -> [Infectious Diseases]
   📄 Article: "Respiratory Syncytial Virus (RSV)" -> [Infectious Diseases]
   📄 Article: "Respiratory Viruses" -> [Infectious Diseases]
   📄 Article: "Rocky Mountain Spotted Fever" -> [Infectious Diseases]
   📄 Article: "Schistosomiasis" -> [Infectious Diseases]
   📄 Article: "Scrub Typhus" -> [Infectious Diseases]
   📄 Article: "Sepsis" -> [Infectious Diseases]
   📄 Article: "Septic Arthritis" -> [Infectious Diseases]
   📄 Article: "Sporotrichosis" -> [Infectious Diseases]
   📄 Article: "Staphylococcus-Associated Glomerulonephritis" -> [Infectious Diseases]
   📄 Article: "Strongyloidiasis" -> [Infectious Diseases]
   📄 Article: "Surgical Site Infections" -> [Infectious Diseases]
   📄 Article: "Syphilis:  Treponema Pallidum Infection" -> [Infectious Diseases]
   📄 Article: "Taenia Solium Infection: Taeniasis And Cysticercosis" -> [Infectious Diseases]
   📄 Article: "Tetanus" -> [Infectious Diseases]
   📄 Article: "TORCH Infections" -> [Infectious Diseases]
   📄 Article: "Toxocariasis" -> [Infectious Diseases]
   📄 Article: "Toxoplasmosis" -> [Infectious Diseases]
   📄 Article: "Trachoma" -> [Infectious Diseases]
   📄 Article: "Trichinellosis" -> [Infectious Diseases]
   📄 Article: "Trichomonas Vaginalis" -> [Infectious Diseases]
   📄 Article: "Urinary Tract Infections (UTIs), Including Pyelonephritis" -> [Infectious Diseases]
   📄 Article: "Urinary Tract Infections In Pregnancy" -> [Infectious Diseases]
   📄 Article: "Vibrio Vulnificus" -> [Infectious Diseases]
   📄 Article: "West Nile Virus" -> [Infectious Diseases]
   📄 Article: "Yersinia Pestis" -> [Infectious Diseases]
   📄 Article: "Zika Virus Infection" -> [Infectious Diseases]
 📁 Folder: "Male Reproductive System"
   📄 Article: "Acute Prostatitis" -> [Male Reproductive System]
   📄 Article: "Anatomy: Male Reproductive System" -> [Male Reproductive System]
   📄 Article: "Anterior And Posterior Urethral Injuries" -> [Male Reproductive System]
   📄 Article: "Antiandrogenic Agents" -> [Male Reproductive System]
   📄 Article: "Balanitis" -> [Male Reproductive System]
   📄 Article: "Benign Prostatic Hyperplasia (BPH)" -> [Male Reproductive System]
   📄 Article: "Chronic Bacterial Prostatitis" -> [Male Reproductive System]
   📄 Article: "Cryptorchidism" -> [Male Reproductive System]
   📄 Article: "Epididymitis" -> [Male Reproductive System]
   📄 Article: "Epispadias" -> [Male Reproductive System]
   📄 Article: "Erectile Dysfunction" -> [Male Reproductive System]
   📄 Article: "Hydrocele" -> [Male Reproductive System]
   📄 Article: "Hypospadias" -> [Male Reproductive System]
   📄 Article: "Klinefelter Syndrome" -> [Male Reproductive System]
   📄 Article: "Male Circumcision" -> [Male Reproductive System]
   📄 Article: "Orchitis" -> [Male Reproductive System]
   📄 Article: "Paraphimosis" -> [Male Reproductive System]
   📄 Article: "Penile Fracture" -> [Male Reproductive System]
   📄 Article: "Peyronie Disease" -> [Male Reproductive System]
   📄 Article: "Phimosis" -> [Male Reproductive System]
   📄 Article: "Premature Ejaculation" -> [Male Reproductive System]
   📄 Article: "Priapism" -> [Male Reproductive System]
   📄 Article: "Prostate Cancer" -> [Male Reproductive System]
   📄 Article: "Spermatocele" -> [Male Reproductive System]
   📄 Article: "Testicular Torsion" -> [Male Reproductive System]
   📄 Article: "Testicular Trauma" -> [Male Reproductive System]
   📄 Article: "Varicocele" -> [Male Reproductive System]
 📁 Folder: "Nephrology"
   📄 Article: "Acid-Base Disorders" -> [Nephrology]
   📄 Article: "Acute Kidney Injury" -> [Nephrology]
   📄 Article: "Alport Syndrome" -> [Nephrology]
   📄 Article: "Anatomy: Urinary System" -> [Nephrology]
   📄 Article: "Bladder Cancer: Urothelial (Transitional Cell) And Nonurothelial Carcinomas" -> [Nephrology]
   📄 Article: "Bladder Rupture" -> [Nephrology]
   📄 Article: "Chronic Kidney Disease: An Overview" -> [Nephrology]
   📄 Article: "Chronic Kidney Disease: Mineral And Bone Disorders" -> [Nephrology]
   📄 Article: "Congenital Renal Anomalies" -> [Nephrology]
   📄 Article: "Congenital Urachal Abnormalities: Cyst, Sinus, And Vesicourethral Diverticulum" -> [Nephrology]
   📄 Article: "Diuretics" -> [Nephrology]
   📄 Article: "Embryology Of The Renal System" -> [Nephrology]
   📄 Article: "Focal Segmental Glomerulosclerosis (FSGS), Including HIV-Associated Nephropathy (HIVAN)" -> [Nephrology]
   📄 Article: "Glomerular Disorders:  An Overview Of Nephritic And Nephrotic Syndrome" -> [Nephrology]
   📄 Article: "Hematuria" -> [Nephrology]
   📄 Article: "Hypernatremia" -> [Nephrology]
   📄 Article: "Hyponatremia" -> [Nephrology]
   📄 Article: "Magnesium Disorders:  Hypermagnesemia And Hypomagnesemia" -> [Nephrology]
   📄 Article: "Membranoproliferative Glomerulonephritis" -> [Nephrology]
   📄 Article: "Membranous Nephropathy" -> [Nephrology]
   📄 Article: "Minimal Change Disease" -> [Nephrology]
   📄 Article: "Nephritic Syndrome: A Comprehensive Overview" -> [Nephrology]
   📄 Article: "Nephritic Syndrome: An Overview" -> [Nephrology]
   📄 Article: "Nephrolithiasis" -> [Nephrology]
   📄 Article: "Nephrotic Syndrome: A Comprehensive Overview" -> [Nephrology]
   📄 Article: "Nephrotic Syndrome: An Overview" -> [Nephrology]
   📄 Article: "Neurogenic Bladder" -> [Nephrology]
   📄 Article: "Phosphate Binders" -> [Nephrology]
   📄 Article: "Polycystic Kidney Disease And Other Renal Cysts" -> [Nephrology]
   📄 Article: "Posterior Urethral Valves" -> [Nephrology]
   📄 Article: "Postoperative Urinary Retention" -> [Nephrology]
   📄 Article: "Poststreptococcal Glomerulonephritis" -> [Nephrology]
   📄 Article: "Potassium Binders" -> [Nephrology]
   📄 Article: "Potassium Disorders:  Hyperkalemia And Hypokalemia" -> [Nephrology]
   📄 Article: "Primary Nocturnal Enuresis" -> [Nephrology]
   📄 Article: "Renal Anatomy And Physiology" -> [Nephrology]
   📄 Article: "Renal Artery Stenosis" -> [Nephrology]
   📄 Article: "Renal Replacement Therapy" -> [Nephrology]
   📄 Article: "Renal Tubular Acidosis" -> [Nephrology]
   📄 Article: "Rhabdomyolysis" -> [Nephrology]
   📄 Article: "Secondary Enuresis" -> [Nephrology]
   📄 Article: "Urethral Stricture" -> [Nephrology]
   📄 Article: "Urinary Tract Obstruction (Obstructive Uropathy) And Hydronephrosis" -> [Nephrology]
   📄 Article: "Vesicoureteral Reflux" -> [Nephrology]
   📄 Article: "Wilms Tumor" -> [Nephrology]
 📁 Folder: "Neurology"
   📄 Article: "Alzheimer Disease" -> [Neurology]
   📄 Article: "Amyotrophic Lateral Sclerosis (ALS) (Lou Gehrig Disease)" -> [Neurology]
   📄 Article: "Autism Spectrum Disorder" -> [Neurology]
   📄 Article: "Autoimmune Encephalitis" -> [Neurology]
   📄 Article: "Autonomic Nervous System" -> [Neurology]
   📄 Article: "Brachial Plexus Injuries" -> [Neurology]
   📄 Article: "Brain Death" -> [Neurology]
   📄 Article: "Brain Herniation Syndromes" -> [Neurology]
   📄 Article: "Brain Tumor Overview" -> [Neurology]
   📄 Article: "Brain Tumors In Adults" -> [Neurology]
   📄 Article: "Caput Succedaneum, Cephalohematoma, And Subgaleal Hemorrhage" -> [Neurology]
   📄 Article: "Carotid Artery Stenosis" -> [Neurology]
   📄 Article: "Cauda Equina Syndrome" -> [Neurology]
   📄 Article: "Cerebral Palsy" -> [Neurology]
   📄 Article: "Cervical Artery Dissection: Carotid And Vertebral Artery Dissection" -> [Neurology]
   📄 Article: "Charcot-Marie-Tooth Disease" -> [Neurology]
   📄 Article: "Chiari Malformations" -> [Neurology]
   📄 Article: "Cluster Headache" -> [Neurology]
   📄 Article: "Concussion And Traumatic Brain Injury" -> [Neurology]
   📄 Article: "Cranial Nerves: Anatomy And Palsies" -> [Neurology]
   📄 Article: "Craniosynostosis" -> [Neurology]
   📄 Article: "Creutzfeldt-Jakob Disease (CJD)" -> [Neurology]
   📄 Article: "Delirium" -> [Neurology]
   📄 Article: "Dementia With Lewy Bodies" -> [Neurology]
   📄 Article: "Duchenne And Becker Muscular Dystrophy" -> [Neurology]
   📄 Article: "Dystonia" -> [Neurology]
   📄 Article: "Epilepsy/Seizures" -> [Neurology]
   📄 Article: "Essential Tremor (And Other Types Of Tremor)" -> [Neurology]
   📄 Article: "Evaluation Of Patient Falls" -> [Neurology]
   📄 Article: "Facial Palsy" -> [Neurology]
   📄 Article: "Febrile Seizure" -> [Neurology]
   📄 Article: "Fetal Alcohol Syndrome" -> [Neurology]
   📄 Article: "Fragile X Syndrome" -> [Neurology]
   📄 Article: "Friedreich Ataxia" -> [Neurology]
   📄 Article: "Frontotemporal Dementia" -> [Neurology]
   📄 Article: "Functional Neurologic Symptom Disorder" -> [Neurology]
   📄 Article: "Guillain-Barré Syndrome" -> [Neurology]
   📄 Article: "Histology: Nerve Tissue" -> [Neurology]
   📄 Article: "Horner Syndrome" -> [Neurology]
   📄 Article: "Huntington Disease" -> [Neurology]
   📄 Article: "Hydrocephalus In Children" -> [Neurology]
   📄 Article: "Idiopathic Intracranial Hypertension (Pseudotumor Cerebri)" -> [Neurology]
   📄 Article: "Intraventricular Hemorrhage" -> [Neurology]
   📄 Article: "Low Back Pain" -> [Neurology]
   📄 Article: "Malignant Hyperthermia" -> [Neurology]
   📄 Article: "Meralgia Paresthetica" -> [Neurology]
   📄 Article: "Migraine Headache" -> [Neurology]
   📄 Article: "Mild Cognitive Impairment" -> [Neurology]
   📄 Article: "Multiple Sclerosis" -> [Neurology]
   📄 Article: "Myasthenia Gravis" -> [Neurology]
   📄 Article: "Myotonic Dystrophy" -> [Neurology]
   📄 Article: "Nerve Physiology" -> [Neurology]
   📄 Article: "Neural Tube Defects" -> [Neurology]
   📄 Article: "Neuroanatomy: Cortical Lobe Function, Basic Tracts, Arterial Anatomy, And Neurolocalization" -> [Neurology]
   📄 Article: "Neuroanatomy: Spinal Cord" -> [Neurology]
   📄 Article: "Neuroembryology" -> [Neurology]
   📄 Article: "Neurofibromatosis Type 1" -> [Neurology]
   📄 Article: "Neuroleptic Malignant Syndrome" -> [Neurology]
   📄 Article: "NF2-Related Schwannomatosis (Formerly Neurofibromatosis Type 2)" -> [Neurology]
   📄 Article: "Normal Pressure Hydrocephalus (NPH)" -> [Neurology]
   📄 Article: "Parkinson Disease And Parkinsonism" -> [Neurology]
   📄 Article: "Pediatric Brain Tumors" -> [Neurology]
   📄 Article: "Pediatric Developmental Milestones" -> [Neurology]
   📄 Article: "Perinatal Asphyxia And Hypoxic Ischemic Encephalopathy" -> [Neurology]
   📄 Article: "Prader-Willi Syndrome And Angelman Syndrome" -> [Neurology]
   📄 Article: "Restless Leg Syndrome (RLS)" -> [Neurology]
   📄 Article: "Rett Syndrome" -> [Neurology]
   📄 Article: "Spinal Cord Compression" -> [Neurology]
   📄 Article: "Spinal Muscle Atrophy (SMA)" -> [Neurology]
   📄 Article: "Stroke" -> [Neurology]
   📄 Article: "Subarachnoid Hemorrhage" -> [Neurology]
   📄 Article: "Subdural And Epidural Hematomas" -> [Neurology]
   📄 Article: "Syringomyelia" -> [Neurology]
   📄 Article: "Tension Headache" -> [Neurology]
   📄 Article: "Transverse Myelitis" -> [Neurology]
   📄 Article: "Trigeminal Neuralgia" -> [Neurology]
   📄 Article: "Tuberous Sclerosis Complex" -> [Neurology]
   📄 Article: "Vascular Dementia" -> [Neurology]
   📄 Article: "Viral Meningitis" -> [Neurology]
   📄 Article: "Visual Pathway" -> [Neurology]
 📁 Folder: "Obstetrics"
   📄 Article: "Abnormal Labor" -> [Obstetrics]
   📄 Article: "Abruptio Placentae (Placental Abruption)" -> [Obstetrics]
   📄 Article: "Acute Fatty Liver Of Pregnancy" -> [Obstetrics]
   📄 Article: "Amniotic Fluid Embolism" -> [Obstetrics]
   📄 Article: "Amniotic Fluid: An Overview" -> [Obstetrics]
   📄 Article: "Antepartum Bleeding: An Overview" -> [Obstetrics]
   📄 Article: "Antepartum Fetal Testing" -> [Obstetrics]
   📄 Article: "Cervical Insufficiency" -> [Obstetrics]
   📄 Article: "Cesarean Delivery" -> [Obstetrics]
   📄 Article: "Common Teratogenic Medications" -> [Obstetrics]
   📄 Article: "Ectopic Pregnancy" -> [Obstetrics]
   📄 Article: "Fetal Development" -> [Obstetrics]
   📄 Article: "Fetal Growth Restriction" -> [Obstetrics]
   📄 Article: "Fetal Heart Rate Tracings" -> [Obstetrics]
   📄 Article: "Fetal Malpresentation" -> [Obstetrics]
   📄 Article: "HELLP Syndrome" -> [Obstetrics]
   📄 Article: "Hydatidiform Mole" -> [Obstetrics]
   📄 Article: "Hydrops Fetalis" -> [Obstetrics]
   📄 Article: "Hyperemesis Gravidarum" -> [Obstetrics]
   📄 Article: "Implantation" -> [Obstetrics]
   📄 Article: "Intraamniotic Infection" -> [Obstetrics]
   📄 Article: "Intrahepatic Cholestasis Of Pregnancy" -> [Obstetrics]
   📄 Article: "Intrauterine Fetal Demise" -> [Obstetrics]
   📄 Article: "Normal Labor" -> [Obstetrics]
   📄 Article: "Operative Vaginal Delivery" -> [Obstetrics]
   📄 Article: "Pain Management During Labor" -> [Obstetrics]
   📄 Article: "Perineal Lacerations" -> [Obstetrics]
   📄 Article: "Physiologic Changes In Pregnancy" -> [Obstetrics]
   📄 Article: "Placenta Accreta Spectrum" -> [Obstetrics]
   📄 Article: "Placenta Previa" -> [Obstetrics]
   📄 Article: "Postpartum Blues, Depression, And Psychosis" -> [Obstetrics]
   📄 Article: "Postpartum Endometritis" -> [Obstetrics]
   📄 Article: "Postpartum Fever: An Overview" -> [Obstetrics]
   📄 Article: "Postpartum Hemorrhage" -> [Obstetrics]
   📄 Article: "Postterm Pregnancy" -> [Obstetrics]
   📄 Article: "Preeclampsia" -> [Obstetrics]
   📄 Article: "Pregnancy Of Unknown Location" -> [Obstetrics]
   📄 Article: "Prenatal Genetic Testing" -> [Obstetrics]
   📄 Article: "Preterm Birth Prevention" -> [Obstetrics]
   📄 Article: "Preterm Labor" -> [Obstetrics]
   📄 Article: "Preterm Prelabor Rupture Of Membranes" -> [Obstetrics]
   📄 Article: "Recurrent Pregnancy Loss" -> [Obstetrics]
   📄 Article: "Routine Postpartum Care" -> [Obstetrics]
   📄 Article: "Routine Prenatal Care" -> [Obstetrics]
   📄 Article: "Shoulder Dystocia" -> [Obstetrics]
   📄 Article: "Spontaneous Abortion" -> [Obstetrics]
   📄 Article: "Twin Gestations" -> [Obstetrics]
   📄 Article: "Uterine Inversion" -> [Obstetrics]
   📄 Article: "Uterine Rupture" -> [Obstetrics]
   📄 Article: "Uterotonic Medications" -> [Obstetrics]
   📄 Article: "Vasa Previa" -> [Obstetrics]
 📁 Folder: "Ophthalmology"
   📄 Article: "Age-Related Macular Degeneration" -> [Ophthalmology]
   📄 Article: "Amaurosis Fugax" -> [Ophthalmology]
   📄 Article: "Amblyopia" -> [Ophthalmology]
   📄 Article: "Anatomy: Eye And Orbit" -> [Ophthalmology]
   📄 Article: "Bacterial Keratitis" -> [Ophthalmology]
   📄 Article: "Blepharitis" -> [Ophthalmology]
   📄 Article: "Cataract" -> [Ophthalmology]
   📄 Article: "Chalazion" -> [Ophthalmology]
   📄 Article: "Congenital Dacryostenosis" -> [Ophthalmology]
   📄 Article: "Corneal Abrasion" -> [Ophthalmology]
   📄 Article: "Dacryocystitis" -> [Ophthalmology]
   📄 Article: "Foreign Body In The Eye" -> [Ophthalmology]
   📄 Article: "Glaucoma" -> [Ophthalmology]
   📄 Article: "Hordeolum" -> [Ophthalmology]
   📄 Article: "Hyphema" -> [Ophthalmology]
   📄 Article: "Lens Dislocation (Ectopia Lentis)" -> [Ophthalmology]
   📄 Article: "Macular Degeneration" -> [Ophthalmology]
   📄 Article: "Neonatal Conjunctivitis" -> [Ophthalmology]
   📄 Article: "Orbital Cellulitis" -> [Ophthalmology]
   📄 Article: "Orbital Compartment Syndrome" -> [Ophthalmology]
   📄 Article: "Orbital Fracture" -> [Ophthalmology]
   📄 Article: "Pterygium" -> [Ophthalmology]
   📄 Article: "Refractive Errors" -> [Ophthalmology]
   📄 Article: "Retinal Detachment" -> [Ophthalmology]
   📄 Article: "Retinitis Pigmentosa" -> [Ophthalmology]
   📄 Article: "Retinoblastoma" -> [Ophthalmology]
   📄 Article: "Retinopathy Of Prematurity" -> [Ophthalmology]
   📄 Article: "Strabismus" -> [Ophthalmology]
   📄 Article: "Subconjunctival Hemorrhage" -> [Ophthalmology]
   📄 Article: "Uveitis" -> [Ophthalmology]
   📄 Article: "Vascular Retinal Disorders" -> [Ophthalmology]
   📄 Article: "Viral Keratitis" -> [Ophthalmology]
   📄 Article: "Vitreous Hemorrhage" -> [Ophthalmology]
 📁 Folder: "Psychiatry"
   📄 Article: "Acute Stress Disorder" -> [Psychiatry]
   📄 Article: "Adjustment Disorder" -> [Psychiatry]
   📄 Article: "Agoraphobia" -> [Psychiatry]
   📄 Article: "Alcohol Use And Its Complications" -> [Psychiatry]
   📄 Article: "Anorexia Nervosa" -> [Psychiatry]
   📄 Article: "Antipsychotics" -> [Psychiatry]
   📄 Article: "Antisocial Personality Disorder" -> [Psychiatry]
   📄 Article: "Attention Deficit Hyperactivity Disorder" -> [Psychiatry]
   📄 Article: "Atypical Antidepressants" -> [Psychiatry]
   📄 Article: "Benzodiazepine Use Disorder" -> [Psychiatry]
   📄 Article: "Binge-Eating Disorder" -> [Psychiatry]
   📄 Article: "Bipolar I Disorder" -> [Psychiatry]
   📄 Article: "Bipolar II Disorder" -> [Psychiatry]
   📄 Article: "Body Dysmorphic Disorder" -> [Psychiatry]
   📄 Article: "Borderline Personality Disorder" -> [Psychiatry]
   📄 Article: "Brief Psychotic Disorder" -> [Psychiatry]
   📄 Article: "Bulimia Nervosa" -> [Psychiatry]
   📄 Article: "Cannabis (Marijuana) Use Disorder" -> [Psychiatry]
   📄 Article: "Cocaine Use Disorder" -> [Psychiatry]
   📄 Article: "Conduct Disorder" -> [Psychiatry]
   📄 Article: "Cyclothymic Disorder" -> [Psychiatry]
   📄 Article: "Defense Mechanisms" -> [Psychiatry]
   📄 Article: "Delivering Bad News" -> [Psychiatry]
   📄 Article: "Delusional Disorder" -> [Psychiatry]
   📄 Article: "Dissociative Disorders" -> [Psychiatry]
   📄 Article: "Elder Abuse" -> [Psychiatry]
   📄 Article: "Electroconvulsive Therapy (ECT)" -> [Psychiatry]
   📄 Article: "Extrapyramidal Symptoms" -> [Psychiatry]
   📄 Article: "Factitious Disorder Imposed On Another" -> [Psychiatry]
   📄 Article: "Factitious Disorder Imposed On Self" -> [Psychiatry]
   📄 Article: "Gambling Disorder" -> [Psychiatry]
   📄 Article: "Gender Dysphoria" -> [Psychiatry]
   📄 Article: "Generalized Anxiety Disorder" -> [Psychiatry]
   📄 Article: "Illness Anxiety Disorder" -> [Psychiatry]
   📄 Article: "Impulse Control Disorders" -> [Psychiatry]
   📄 Article: "Involuntary Psychiatric Hospitalization" -> [Psychiatry]
   📄 Article: "Lithium" -> [Psychiatry]
   📄 Article: "Lysergic Acid Diethylamide (LSD)" -> [Psychiatry]
   📄 Article: "Major Depressive Disorder" -> [Psychiatry]
   📄 Article: "Malingering" -> [Psychiatry]
   📄 Article: "Monoamine Oxidase Inhibitors (MAOIs)" -> [Psychiatry]
   📄 Article: "Motivational Interviewing" -> [Psychiatry]
   📄 Article: "Narcolepsy" -> [Psychiatry]
   📄 Article: "Obsessive-Compulsive Disorder" -> [Psychiatry]
   📄 Article: "Opioid Use Disorder" -> [Psychiatry]
   📄 Article: "Oppositional Defiant Disorder" -> [Psychiatry]
   📄 Article: "Other Mood Stabilizers For Bipolar Disorder" -> [Psychiatry]
   📄 Article: "Panic Disorder" -> [Psychiatry]
   📄 Article: "Persistent Depressive Disorder" -> [Psychiatry]
   📄 Article: "Personality Disorders" -> [Psychiatry]
   📄 Article: "Pharmacotherapy For Attention Deficit Hyperactivity Disorder (ADHD)" -> [Psychiatry]
   📄 Article: "Phencyclidine (PCP)" -> [Psychiatry]
   📄 Article: "Posttraumatic Stress Disorder" -> [Psychiatry]
   📄 Article: "Schizoaffective Disorder" -> [Psychiatry]
   📄 Article: "Schizophrenia" -> [Psychiatry]
   📄 Article: "Schizophreniform Disorder" -> [Psychiatry]
   📄 Article: "Seasonal Affective Disorder" -> [Psychiatry]
   📄 Article: "Secondary Medical Causes Of Depression" -> [Psychiatry]
   📄 Article: "Selective Serotonin Reuptake Inhibitors (SSRIs)" -> [Psychiatry]
   📄 Article: "Separation Anxiety Disorder" -> [Psychiatry]
   📄 Article: "Serotonin Toxicity" -> [Psychiatry]
   📄 Article: "Serotonin-Norepinephrine Reuptake Inhibitors (SNRIs)" -> [Psychiatry]
   📄 Article: "Sleep Disorders" -> [Psychiatry]
   📄 Article: "Social Anxiety Disorder" -> [Psychiatry]
   📄 Article: "Somatic Symptom Disorder" -> [Psychiatry]
   📄 Article: "Specific Phobias" -> [Psychiatry]
   📄 Article: "Stages Of Behavior Change" -> [Psychiatry]
   📄 Article: "Stimulant Use Disorder" -> [Psychiatry]
   📄 Article: "Suicidal Ideation And Risk Assessment" -> [Psychiatry]
   📄 Article: "Tourette Syndrome" -> [Psychiatry]
   📄 Article: "Trichotillomania" -> [Psychiatry]
   📄 Article: "Tricyclic Antidepressants" -> [Psychiatry]
   📄 Article: "Uncomplicated Grief And Prolonged Grief Disorder" -> [Psychiatry]
 📁 Folder: "Pulmonary & Critical Care"
   📄 Article: "Acute Respiratory Distress Syndrome (ARDS)" -> [Pulmonary & Critical Care]
   📄 Article: "Air Embolism" -> [Pulmonary & Critical Care]
   📄 Article: "Alpha-1 Antitrypsin Deficiency" -> [Pulmonary & Critical Care]
   📄 Article: "Asbestos" -> [Pulmonary & Critical Care]
   📄 Article: "Asthma: Management" -> [Pulmonary & Critical Care]
   📄 Article: "Asthma: Pathophysiology And Diagnosis" -> [Pulmonary & Critical Care]
   📄 Article: "Atelectasis" -> [Pulmonary & Critical Care]
   📄 Article: "Bronchitis" -> [Pulmonary & Critical Care]
   📄 Article: "Bronchopulmonary Dysplasia" -> [Pulmonary & Critical Care]
   📄 Article: "Chest Tubes" -> [Pulmonary & Critical Care]
   📄 Article: "Chronic Cough" -> [Pulmonary & Critical Care]
   📄 Article: "Chronic Obstructive Pulmonary Disease (COPD)" -> [Pulmonary & Critical Care]
   📄 Article: "Congenital Diaphragmatic Hernia" -> [Pulmonary & Critical Care]
   📄 Article: "Cystic Fibrosis" -> [Pulmonary & Critical Care]
   📄 Article: "Decompression Illness" -> [Pulmonary & Critical Care]
   📄 Article: "Drowning (Submersion Injury)" -> [Pulmonary & Critical Care]
   📄 Article: "Fat Embolism Syndrome" -> [Pulmonary & Critical Care]
   📄 Article: "Hemoptysis" -> [Pulmonary & Critical Care]
   📄 Article: "High Altitude Illness" -> [Pulmonary & Critical Care]
   📄 Article: "Hypersensitivity Pneumonitis" -> [Pulmonary & Critical Care]
   📄 Article: "Hypoxemia: Diagnosis And Management" -> [Pulmonary & Critical Care]
   📄 Article: "Hypoxemia: Physiology" -> [Pulmonary & Critical Care]
   📄 Article: "Idiopathic Pulmonary Fibrosis (IPF)" -> [Pulmonary & Critical Care]
   📄 Article: "Influenza" -> [Pulmonary & Critical Care]
   📄 Article: "Inhaled Corticosteroids And Bronchodilators" -> [Pulmonary & Critical Care]
   📄 Article: "Interstitial Lung Disease" -> [Pulmonary & Critical Care]
   📄 Article: "Lactic Acidosis" -> [Pulmonary & Critical Care]
   📄 Article: "Large Airway Obstructions" -> [Pulmonary & Critical Care]
   📄 Article: "Lung Embryology And Congenital Malformations" -> [Pulmonary & Critical Care]
   📄 Article: "Mechanical Ventilation" -> [Pulmonary & Critical Care]
   📄 Article: "Meconium Aspiration Syndrome" -> [Pulmonary & Critical Care]
   📄 Article: "Neonatal Respiratory Distress Syndrome" -> [Pulmonary & Critical Care]
   📄 Article: "On The Wards: Respiratory Distress" -> [Pulmonary & Critical Care]
   📄 Article: "Persistent Pulmonary Hypertension Of The Newborn" -> [Pulmonary & Critical Care]
   📄 Article: "Pleural Effusion" -> [Pulmonary & Critical Care]
   📄 Article: "Pneumothorax" -> [Pulmonary & Critical Care]
   📄 Article: "Pulmonary Function Testing" -> [Pulmonary & Critical Care]
   📄 Article: "Pulmonary Hypertension" -> [Pulmonary & Critical Care]
   📄 Article: "Pulmonary Interstitial Emphysema" -> [Pulmonary & Critical Care]
   📄 Article: "Pulmonary Physiology: Gas Exchange" -> [Pulmonary & Critical Care]
   📄 Article: "Pulmonary Physiology: Hypoxemia" -> [Pulmonary & Critical Care]
   📄 Article: "Pulmonary Physiology: Oxygen-Hemoglobin Dissociation Curve" -> [Pulmonary & Critical Care]
   📄 Article: "Pulmonary Physiology: Pulmonary Circulation" -> [Pulmonary & Critical Care]
   📄 Article: "Pulmonary Physiology: Respiratory Mechanics" -> [Pulmonary & Critical Care]
   📄 Article: "Pulmonary Physiology: Respiratory Neurobiology" -> [Pulmonary & Critical Care]
   📄 Article: "Pulmonary Vasodilator Therapy" -> [Pulmonary & Critical Care]
   📄 Article: "Sarcoidosis" -> [Pulmonary & Critical Care]
   📄 Article: "Sleep Apnea" -> [Pulmonary & Critical Care]
   📄 Article: "Smoking Cessation" -> [Pulmonary & Critical Care]
   📄 Article: "Surgical Airway: Tracheostomy And Cricothyrotomy" -> [Pulmonary & Critical Care]
   📄 Article: "Transient Tachypnea Of The Newborn" -> [Pulmonary & Critical Care]
   📄 Article: "Trauma: General Approach To The Trauma Patient" -> [Pulmonary & Critical Care]
   📄 Article: "Trauma: Major Extremity Trauma" -> [Pulmonary & Critical Care]
   📄 Article: "Trauma: Penetrating Thoracic Trauma" -> [Pulmonary & Critical Care]
   📄 Article: "Vasopressors And Inotropes" -> [Pulmonary & Critical Care]
   📄 Article: "Venous Thromboembolism (VTE):  Deep Venous Thrombosis (DVT) And Pulmonary Embolism (PE)" -> [Pulmonary & Critical Care]
 📁 Folder: "Rheumatology/Orthopedics"
   📄 Article: "Achondroplasia" -> [Rheumatology/Orthopedics]
   📄 Article: "Adhesive Capsulitis" -> [Rheumatology/Orthopedics]
   📄 Article: "Anatomy: Knee" -> [Rheumatology/Orthopedics]
   📄 Article: "Anatomy: Shoulder" -> [Rheumatology/Orthopedics]
   📄 Article: "Anatomy: Vertebrae" -> [Rheumatology/Orthopedics]
   📄 Article: "Ankylosing Spondylitis" -> [Rheumatology/Orthopedics]
   📄 Article: "Autoinflammatory Diseases (Including Familial Mediterranean Fever)" -> [Rheumatology/Orthopedics]
   📄 Article: "Behçet Disease" -> [Rheumatology/Orthopedics]
   📄 Article: "Benign And Malignant Bone Tumors" -> [Rheumatology/Orthopedics]
   📄 Article: "Bursitis" -> [Rheumatology/Orthopedics]
   📄 Article: "Carpal Tunnel Syndrome" -> [Rheumatology/Orthopedics]
   📄 Article: "Carpal Tunnel Syndrome And Median Nerve Compression" -> [Rheumatology/Orthopedics]
   📄 Article: "Cervical Spine Clearance" -> [Rheumatology/Orthopedics]
   📄 Article: "Clostridial Myonecrosis" -> [Rheumatology/Orthopedics]
   📄 Article: "Common Adult Foot Deformities" -> [Rheumatology/Orthopedics]
   📄 Article: "Compartment Syndrome" -> [Rheumatology/Orthopedics]
   📄 Article: "Congenital Clubfoot (Congenital Talipes Equinovarus)" -> [Rheumatology/Orthopedics]
   📄 Article: "Cryoglobulinemia" -> [Rheumatology/Orthopedics]
   📄 Article: "Crystal Arthropathies: Gout And Pseudogout" -> [Rheumatology/Orthopedics]
   📄 Article: "De Quervain Tendinopathy" -> [Rheumatology/Orthopedics]
   📄 Article: "Developmental Dysplasia Of The Hip" -> [Rheumatology/Orthopedics]
   📄 Article: "Dupuytren Contracture" -> [Rheumatology/Orthopedics]
   📄 Article: "Ehlers-Danlos Syndrome (EDS)" -> [Rheumatology/Orthopedics]
   📄 Article: "Elbow Tendinopathy" -> [Rheumatology/Orthopedics]
   📄 Article: "Evaluation Of Pediatric Hip Pain" -> [Rheumatology/Orthopedics]
   📄 Article: "Ewing Sarcoma" -> [Rheumatology/Orthopedics]
   📄 Article: "Fibromyalgia" -> [Rheumatology/Orthopedics]
   📄 Article: "Fracture Patterns In Children" -> [Rheumatology/Orthopedics]
   📄 Article: "Ganglion Cyst" -> [Rheumatology/Orthopedics]
   📄 Article: "Genu Valgum And Varum" -> [Rheumatology/Orthopedics]
   📄 Article: "Giant Cell (Temporal) Arteritis" -> [Rheumatology/Orthopedics]
   📄 Article: "Giant Cell Tumor" -> [Rheumatology/Orthopedics]
   📄 Article: "Growing Pains" -> [Rheumatology/Orthopedics]
   📄 Article: "Heel Pain" -> [Rheumatology/Orthopedics]
   📄 Article: "Hip Dislocations" -> [Rheumatology/Orthopedics]
   📄 Article: "Hip Fractures" -> [Rheumatology/Orthopedics]
   📄 Article: "Idiopathic Inflammatory Myopathies: Dermatomyositis And Polymyositis" -> [Rheumatology/Orthopedics]
   📄 Article: "Juvenile Idiopathic Arthritis" -> [Rheumatology/Orthopedics]
   📄 Article: "Kawasaki Disease" -> [Rheumatology/Orthopedics]
   📄 Article: "Knee Trauma" -> [Rheumatology/Orthopedics]
   📄 Article: "Laboratory Testing In Autoimmune Rheumatic Disease: Inflammatory Markers, Autoantibodies, And Others" -> [Rheumatology/Orthopedics]
   📄 Article: "Legg-Calvé-Perthes Disease" -> [Rheumatology/Orthopedics]
   📄 Article: "Limb Development Disorders" -> [Rheumatology/Orthopedics]
   📄 Article: "Lumbosacral Plexus" -> [Rheumatology/Orthopedics]
   📄 Article: "Mitochondrial Myopathies" -> [Rheumatology/Orthopedics]
   📄 Article: "Neck Pain" -> [Rheumatology/Orthopedics]
   📄 Article: "Nonaccidental Trauma In Children" -> [Rheumatology/Orthopedics]
   📄 Article: "Osgood-Schlatter Disease" -> [Rheumatology/Orthopedics]
   📄 Article: "Osteoarthritis" -> [Rheumatology/Orthopedics]
   📄 Article: "Osteogenesis Imperfecta" -> [Rheumatology/Orthopedics]
   📄 Article: "Overuse Injuries Of The Knee" -> [Rheumatology/Orthopedics]
   📄 Article: "Pediatric Spinal Deformities: Scoliosis, Kyphosis, And Lordosis" -> [Rheumatology/Orthopedics]
   📄 Article: "Pelvic Fractures" -> [Rheumatology/Orthopedics]
   📄 Article: "Plantar Fasciitis" -> [Rheumatology/Orthopedics]
   📄 Article: "Polyarteritis Nodosa" -> [Rheumatology/Orthopedics]
   📄 Article: "Polymyalgia Rheumatica" -> [Rheumatology/Orthopedics]
   📄 Article: "Popliteal (Baker) Cyst" -> [Rheumatology/Orthopedics]
   📄 Article: "Radial Head Subluxation" -> [Rheumatology/Orthopedics]
   📄 Article: "Raynaud Phenomenon" -> [Rheumatology/Orthopedics]
   📄 Article: "Reactive Arthritis" -> [Rheumatology/Orthopedics]
   📄 Article: "Rotator Cuff Syndrome" -> [Rheumatology/Orthopedics]
   📄 Article: "Scleroderma And CREST Syndrome" -> [Rheumatology/Orthopedics]
   📄 Article: "Shoulder Dislocations" -> [Rheumatology/Orthopedics]
   📄 Article: "Sjögren Disease" -> [Rheumatology/Orthopedics]
   📄 Article: "Skeletal Muscle Relaxants: Antispastic And Spasmolytic Agents" -> [Rheumatology/Orthopedics]
   📄 Article: "Slipped Capital Femoral Epiphysis" -> [Rheumatology/Orthopedics]
   📄 Article: "Spinal Epidural Abscess" -> [Rheumatology/Orthopedics]
   📄 Article: "Spondylosis, Spondylolysis, And Spondylolisthesis" -> [Rheumatology/Orthopedics]
   📄 Article: "Systemic Lupus Erythematous" -> [Rheumatology/Orthopedics]
   📄 Article: "Thromboangiitis Obliterans (Buerger Disease)" -> [Rheumatology/Orthopedics]
   📄 Article: "Transient Synovitis" -> [Rheumatology/Orthopedics]
   📄 Article: "Traumatic Hand And Finger Injuries" -> [Rheumatology/Orthopedics]
   📄 Article: "Traumatic Nail Injuries" -> [Rheumatology/Orthopedics]
   📄 Article: "Upper And Lower Extremity Fractures" -> [Rheumatology/Orthopedics]
   📄 Article: "Vasculitis: An Overview" -> [Rheumatology/Orthopedics]
 📁 Folder: "Social Sciences"
   📄 Article: "Advance Care Planning" -> [Social Sciences]
   📄 Article: "Ethical Principles Of Medicine" -> [Social Sciences]
   📄 Article: "Financing Of The US Health Care System" -> [Social Sciences]
   📄 Article: "Hospice Care" -> [Social Sciences]
   📄 Article: "Human Subjects Research Ethics" -> [Social Sciences]
   📄 Article: "Informed Consent In Medicine" -> [Social Sciences]
   📄 Article: "Medical Decision-Making Capacity" -> [Social Sciences]
   📄 Article: "Medical Errors" -> [Social Sciences]
   📄 Article: "Medical Malpractice" -> [Social Sciences]
   📄 Article: "Palliative Care" -> [Social Sciences]
   📄 Article: "Patient Confidentiality And Privacy" -> [Social Sciences]
   📄 Article: "Physician Misconduct" -> [Social Sciences]
   📄 Article: "Quality Improvement Overview" -> [Social Sciences]
   📄 Article: "Quality Improvement: An Overview" -> [Social Sciences]
   📄 Article: "Quality Improvement: Measures And Error Analysis" -> [Social Sciences]
   📄 Article: "Transitions Of Care: Post-Acute-Care Facilities" -> [Social Sciences]
 📁 Folder: "Toxicology"
   📄 Article: "Acetaminophen Toxicity" -> [Toxicology]
   📄 Article: "Anticholinergic Toxicity" -> [Toxicology]
   📄 Article: "Arsenic Poisoning" -> [Toxicology]
   📄 Article: "Arthropod Bites And Infestations" -> [Toxicology]
   📄 Article: "Carbon Monoxide Poisoning" -> [Toxicology]
   📄 Article: "Caustic Ingestions" -> [Toxicology]
   📄 Article: "Cold Injuries" -> [Toxicology]
   📄 Article: "Cyanide Poisoning" -> [Toxicology]
   📄 Article: "Electrical Injuries, Including Lightning Injuries" -> [Toxicology]
   📄 Article: "Ethylene Glycol Poisoning" -> [Toxicology]
   📄 Article: "Heat Stroke" -> [Toxicology]
   📄 Article: "Heavy Metal Toxicity:  Lead, Iron, Mercury, And Arsenic" -> [Toxicology]
   📄 Article: "Hydrocarbon Ingestion" -> [Toxicology]
   📄 Article: "Lead Poisoning" -> [Toxicology]
   📄 Article: "Methanol Poisoning" -> [Toxicology]
   📄 Article: "Nicotine Poisoning" -> [Toxicology]
   📄 Article: "Organophosphate Poisoning" -> [Toxicology]
   📄 Article: "Radiation Exposure" -> [Toxicology]
   📄 Article: "Reye Syndrome" -> [Toxicology]
   📄 Article: "Salicylate (Aspirin) Toxicity" -> [Toxicology]
   📄 Article: "Scombroid Poisoning (Histamine Fish Poisoning)" -> [Toxicology]
   📄 Article: "Snakebites" -> [Toxicology]
   📄 Article: "Spider Bites" -> [Toxicology]
 📁 Folder: "Embryology"
   📄 Article: "Beckwith-Wiedemann Syndrome" -> [Embryology]
   📄 Article: "Embryologic Derivatives: Gastrulation, Neurulation, And The Primary Germ Layers" -> [Embryology]
   📄 Article: "The Pharyngeal Apparatus: Pharyngeal Arches, Pouches, And Clefts" -> [Embryology]
   📄 Article: "Trisomy 13 (Patau Syndrome)" -> [Embryology]
   📄 Article: "Trisomy 18 (Edwards Syndrome)" -> [Embryology]
   📄 Article: "Trisomy 21 (Down Syndrome)" -> [Embryology]
   📄 Article: "Types Of Congenital Anomalies" -> [Embryology]
 📁 Folder: "Pharmacology"
   📄 Article: "COX-1 And COX-2 Inhibitors" -> [Pharmacology]
   📄 Article: "Cytochrome P450 Enzyme System" -> [Pharmacology]
   📄 Article: "Intravenous And Inhaled Anesthetics" -> [Pharmacology]
   📄 Article: "Local Anesthetic Agents" -> [Pharmacology]
   📄 Article: "Management Of Acute Pain" -> [Pharmacology]
   📄 Article: "Nonsteroidal Anti-Inflammatory Drugs (NSAIDs)" -> [Pharmacology]
   📄 Article: "Performance Enhancing Drugs" -> [Pharmacology]
   📄 Article: "Pharmacodynamics" -> [Pharmacology]
   📄 Article: "Pharmacogenomics" -> [Pharmacology]
   📄 Article: "Pharmacokinetics" -> [Pharmacology]
   📄 Article: "Skeletal Muscle Relaxants: Neuromuscular Blocking Agents" -> [Pharmacology]
 📁 Folder: "Preclinical/Basic Sciences"
   📄 Article: "Acute And Chronic Inflammation" -> [Preclinical/Basic Sciences]
   📄 Article: "Alkaptonuria" -> [Preclinical/Basic Sciences]
   📄 Article: "Biochemistry: Amino Acids" -> [Preclinical/Basic Sciences]
   📄 Article: "Biochemistry: Carbohydrate Metabolism" -> [Preclinical/Basic Sciences]
   📄 Article: "Biochemistry: Major Metabolic Pathways" -> [Preclinical/Basic Sciences]
   📄 Article: "Biochemistry: Protein Catabolism And Nitrogen Disposal" -> [Preclinical/Basic Sciences]
   📄 Article: "Biochemistry: Tricarboxylic Acid (TCA) Cycle" -> [Preclinical/Basic Sciences]
   📄 Article: "Biochemistry: Urea Cycle" -> [Preclinical/Basic Sciences]
   📄 Article: "Cell And Gene Therapy" -> [Preclinical/Basic Sciences]
   📄 Article: "Cell Biology: Cell Adaptation" -> [Preclinical/Basic Sciences]
   📄 Article: "Cell Biology: Cell Death" -> [Preclinical/Basic Sciences]
   📄 Article: "Cell Biology: Cell Receptor Signaling" -> [Preclinical/Basic Sciences]
   📄 Article: "Cell Biology: Cytopathology" -> [Preclinical/Basic Sciences]
   📄 Article: "Cell Biology: Cytoskeleton" -> [Preclinical/Basic Sciences]
   📄 Article: "Cell Biology: Disposal And Recycling Pathway" -> [Preclinical/Basic Sciences]
   📄 Article: "Cell Biology: Junctions And Polarity" -> [Preclinical/Basic Sciences]
   📄 Article: "Cell Biology: Mitochondria" -> [Preclinical/Basic Sciences]
   📄 Article: "Cell Biology: Overview Of Cell Structure" -> [Preclinical/Basic Sciences]
   📄 Article: "Cell Biology: Purine And Pyrimidine Metabolism" -> [Preclinical/Basic Sciences]
   📄 Article: "Cell Biology: Secretory Pathway (Endoplasmic Reticulum And Golgi Apparatus)" -> [Preclinical/Basic Sciences]
   📄 Article: "Cell Division: Meiosis, Mitosis, And Cell Cycle Regulation" -> [Preclinical/Basic Sciences]
   📄 Article: "Cellular And Molecular Aspects Of Aging" -> [Preclinical/Basic Sciences]
   📄 Article: "DNA And The Central Dogma: Gene Transcription And Translation" -> [Preclinical/Basic Sciences]
   📄 Article: "Extracellular Matrix And Connective Tissue" -> [Preclinical/Basic Sciences]
   📄 Article: "Fructose Metabolism And Associated Disorders" -> [Preclinical/Basic Sciences]
   📄 Article: "Genetics: DNA Damage And Repair" -> [Preclinical/Basic Sciences]
   📄 Article: "Genetics: Inheritance Patterns" -> [Preclinical/Basic Sciences]
   📄 Article: "Genetics: Mutations" -> [Preclinical/Basic Sciences]
   📄 Article: "Glycogen Storage Diseases" -> [Preclinical/Basic Sciences]
   📄 Article: "Histology: Epithelial Tissue" -> [Preclinical/Basic Sciences]
   📄 Article: "Homocysteine And Homocystinuria" -> [Preclinical/Basic Sciences]
   📄 Article: "Lac Operon" -> [Preclinical/Basic Sciences]
   📄 Article: "Lysosomal Storage Diseases" -> [Preclinical/Basic Sciences]
   📄 Article: "Maple Syrup Urine Disease" -> [Preclinical/Basic Sciences]
   📄 Article: "Molecular Biology Laboratory Techniques" -> [Preclinical/Basic Sciences]
   📄 Article: "Muscle Physiology" -> [Preclinical/Basic Sciences]
   📄 Article: "Organic Acidemias" -> [Preclinical/Basic Sciences]
   📄 Article: "Peptides And Proteins" -> [Preclinical/Basic Sciences]
   📄 Article: "Physiology: Core Principles" -> [Preclinical/Basic Sciences]
   📄 Article: "Population Genetics" -> [Preclinical/Basic Sciences]
 📁 Folder: "Anatomy & Histology"
   📄 Article: "Anatomy: Elbow/Forearm" -> [Anatomy & Histology]
   📄 Article: "Anatomy: Foot And Ankle" -> [Anatomy & Histology]
   📄 Article: "Anatomy: Hand" -> [Anatomy & Histology]
   📄 Article: "Anatomy: Hip" -> [Anatomy & Histology]
   📄 Article: "Anatomy: Layers Of The Back" -> [Anatomy & Histology]
   📄 Article: "Anatomy: Oral Cavity And Oropharynx" -> [Anatomy & Histology]
   📄 Article: "Anatomy: Skull And Cranial Cavity" -> [Anatomy & Histology]
   📄 Article: "Anatomy: Thorax And Thoracic Cavity" -> [Anatomy & Histology]
   📄 Article: "Anatomy: Wrist" -> [Anatomy & Histology]
 📁 Folder: "Cell Bio, Biochem, Genetics"
 📁 Folder: "Osteopathic Principles"
   📄 Article: "Chapman Points" -> [Osteopathic Principles]
   📄 Article: "Cranial Osteopathy" -> [Osteopathic Principles]
   📄 Article: "Osteopathic Manipulative Treatment: Cervical Spine" -> [Osteopathic Principles]
   📄 Article: "Osteopathic Manipulative Treatment: Innominates" -> [Osteopathic Principles]
   📄 Article: "Osteopathic Manipulative Treatment: Lower Extremities" -> [Osteopathic Principles]
   📄 Article: "Osteopathic Manipulative Treatment: Lumbar Spine" -> [Osteopathic Principles]
   📄 Article: "Osteopathic Manipulative Treatment: Sacrum" -> [Osteopathic Principles]
   📄 Article: "Osteopathic Manipulative Treatment: Scoliosis" -> [Osteopathic Principles]
   📄 Article: "Osteopathic Manipulative Treatment: Short-Leg Syndrome (Leg-Length Discrepancy)" -> [Osteopathic Principles]
   📄 Article: "Osteopathic Manipulative Treatment: Techniques" -> [Osteopathic Principles]
   📄 Article: "Osteopathic Manipulative Treatment: Tender Points And Counterstrain" -> [Osteopathic Principles]
   📄 Article: "Osteopathic Manipulative Treatment: Thoracic Spine" -> [Osteopathic Principles]
   📄 Article: "Osteopathic Manipulative Treatment: Upper Extremities" -> [Osteopathic Principles]
   📄 Article: "Somatic Dysfunctions" -> [Osteopathic Principles]
   📄 Article: "Tender Points, Trigger Points, And Chapman Points" -> [Osteopathic Principles]
   📄 Article: "Viscerosomatic Reflexes" -> [Osteopathic Principles]
 📁 Folder: "Physiology"
   📄 Article: "Thermoregulation" -> [Physiology]
   📄 Article: "Bookmarks" -> [Physiology]
"""

folders = ["Uncategorized"]
folders_set = set(["Uncategorized"])
articles = []

current_folder = "Uncategorized"
art_count = 0

for line in user_pasted_text.splitlines():
    line = line.strip()
    if not line:
        continue

    folder_match = re.search(r'📁\s*Folder:\s*"([^"]+)"', line)
    if folder_match:
        f_name = folder_match.group(1).strip()
        if f_name and f_name not in folders_set and not f_name.startswith("${"):
            current_folder = f_name
            folders.append(f_name)
            folders_set.add(f_name)
        continue

    article_match = re.search(r'📄\s*Article:\s*"([^"]+)"\s*(?:->\s*\[([^\]]+)\])?', line)
    if article_match:
        title = article_match.group(1).strip()
        folder = article_match.group(2).strip() if article_match.group(2) else current_folder

        if title.startswith("${") or title.lower() in ["bookmarks", "search medical library"]:
            continue

        if folder not in folders_set and not folder.startswith("${"):
            folders.append(folder)
            folders_set.add(folder)

        if not any(a["title"].lower() == title.lower() for a in articles):
            art_count += 1
            articles.append({
                "id": f"master-{art_count:04d}",
                "title": title,
                "folderName": folder,
                "fetched": False,
                "markdown": None
            })

catalog = {
    "folders": folders,
    "articles": articles
}

with open("library_data/library.json", "w", encoding="utf-8") as f:
    json.dump(catalog, f, indent=2, ensure_ascii=False)

print(f"DONE! Generated library.json with {len(folders)} Folders and {len(articles)} Articles!")
